matrix:
  # Current tests
  # - Linux, dmd-2.090.1
  # - Linux, dmd (latest)
  # - Linux, ldc-1.20.0, lto/pgo
  # - Linux, ldc-1.20.0          (Default because LTO only fails)
  # - Linux, ldc-1.20.0, lto     (LTO only because LTO/PGO fails)
  # - Linux, ldc (latest), lto/pgo
  # - OS X, dmd-2.090.1
  # - OS X, dmd (latest)
  # - OS X,  ldc-1.20.0, lto/pgo
  # - OS X,  ldc (latest) lto/pgo
  # Additional cron tests
  # - OS X, ldc-beta lto/pgo
  # - OS X, ldc-latest-ci lto
  # - Linux, ldc-beta lto/pgo
  # - Linux, ldc-latest-ci lto
  include:
    - os: linux
      dist: xenial
      group: travis_latest
      language: d
      env: CLI_TEST=1
      d: dmd-2.090.1
    - os: linux
      dist: xenial
      group: travis_latest
      language: d
      env: CLI_TEST=1
      d: dmd
    - os: linux
      dist: xenial
      group: travis_latest
      language: d
      env: LTO_PGO=1
      d: ldc-1.20.0
    - os: linux
      dist: xenial
      group: travis_latest
      language: d
      env: CLI_TEST=1
      d: ldc-1.20.0
    - os: linux
      dist: xenial
      group: travis_latest
      language: d
      env: LTO=1
      d: ldc-1.20.0
    - os: linux
      dist: xenial
      group: travis_latest
      language: d
      env: LTO_PGO=1
      d: ldc
    - os: osx
      osx_image: xcode11.1
      group: travis_latest
      language: d
      d: dmd-2.090.1
      env: CLI_TEST=1
    - os: osx
      osx_image: xcode11.1
      group: travis_latest
      language: d
      d: dmd
      env: CLI_TEST=1
    - os: osx
      osx_image: xcode11.1
      group: travis_latest
      language: d
      d: ldc-1.20.0
      env: LTO_PGO=1
    - os: osx
      osx_image: xcode11.1
      group: travis_latest
      language: d
      d: ldc
      env: LTO_PGO=1
    - os: osx
      osx_image: xcode11.1
      group: travis_latest
      language: d
      d: ldc-beta
      env: LTO_PGO=1
      if: type IN (cron)
    - os: osx
      osx_image: xcode11.1
      group: travis_latest
      language: d
      d: ldc-latest-ci
      env: LTO=1
      if: type IN (cron)
    - os: linux
      dist: xenial
      group: travis_latest
      language: d
      d: ldc-beta
      env: LTO_PGO=1
      if: type IN (cron)
    - os: linux
      dist: xenial
      group: travis_latest
      language: d
      d: ldc-latest-ci
      env: LTO=1
      if: type IN (cron)
script:
- if [[ "$LTO_PGO" == "1" ]]; then
    dub build --compiler=ldc2 --build=release-lto-pgo --combined && dub build --build=cli-test --combined;
  fi
- if [[ "$LTO" == "1" ]]; then
    dub build --compiler=ldc2 --build=release-lto --combined && dub build --build=cli-test --combined;
  fi
- if [[ "$CLI_TEST" == "1" ]]; then
    dub build --build=cli-test --combined;
  fi
