matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      group: travis_latest
      language: d
      d: ldc
    - os: linux
      dist: xenial
      group: travis_latest
      language: d
      d: ldc
    - os: osx
      osx_image: xcode10.2
      group: travis_latest
      language: d
      d: ldc-beta
      if: type IN (cron)
    - os: linux
      dist: xenial
      group: travis_latest
      language: d
      d: ldc-beta
      if: type IN (cron)
    - os: osx
      osx_image: xcode10.2
      group: travis_latest
      language: d
      d: ldc-latest-ci
      if: type IN (cron)
    - os: linux
      dist: xenial
      group: travis_latest
      language: d
      d: ldc-latest-ci
      if: type IN (cron)
script:
- dub build --compiler=ldc2 --build=release-lto-pgo --combined && dub build --build=cli-test --combined
